### ISSUE TITLE
Support For Head Tags

### ISSUE THREAD

**Issue by mrmaddotta** [spatie/laravel-server-side-rendering#18]
Hello

Been playing around with this for a few days and its super awesome!! Thanks for the time put in to get this working :)

Is there any support for using a Vue package to update tags in the html head? Or rather, what is the best way to do this?

I have take a look at the [vue-meta](https://github.com/declandewet/vue-meta) package but seem to be running into issues. Their docs also explain things from a node backend which leaves me here.

Any help would be appreciated :)

**Comment by sebastiandedeyne** [comment]
Hi!

This is an interesting issue. I don't really know how it'd be possible to work around this. If I've got some spare time this week, I'll try to set up an example repo and play around a bit :)

**Comment by mrmaddotta** [comment]
Thanks!

A work around I have been thinking about would be to have routes & controllers in Laravel to mimic the routing on the client-side where you could specify the head content (title, description, og tags etc) based on the route (I am already leaning in this direction to get dynamic content hydrated into the vue store).

It feels gross to have this duplication, but dependant on the size of one's application (route wise), this could be playable?

Any who, looking forward to your response and thanks again for the time spent on this package!

**Comment by sebastiandedeyne** [comment]
Looked into this. It's not really feasible today in a hybrid PHP / JS app.

If you can afford to _fully_ server side render your view (so no Blade at all), you could move all your html to the server entry like this example: https://github.com/declandewet/vue-meta#simple-rendering-with-rendertostring. In that case, you might as well use a Node server instead of this package though...

I want to expand the `spatie/server-side-rendering` package at some point to `dispatch` the html and an additional context object with a second argument, then we could return the meta tags and dump them somewhere else in the view, but that requires some significant changes to the package's internals.

Unfortunately it's not a high priority for me now, don't expect the new features any time soon, but I'm open to a PR or suggestions!
