### ISSUE TITLE
Will this work with Laravel Vapor?

### ISSUE THREAD

**Issue by jcsoriano** [spatie/laravel-server-side-rendering#44]
Hi, thank you for this wonderful package! I've been a big fan of Spatie's open source packages, you're really making the PHP / Laravel ecosystem a much better place to work in. 

We've been using this package successfully on a Forge setup. But do you think this will work with Laravel [Vapor](https://vapor.laravel.com/) / Lambda? If not out of the box, do you have ideas on any workarounds to make it work?

**Comment by connecteev** [comment]
@jcsoriano I have the same question. 

Also one for you, since SSR on PHP is "unchartered territory" as the README says.
I am curious how you use this laravel-server-side-rendering package for SSR on your production setup. Does it work as well as Nuxt.js on production? Is it quick to load? Is it stable?
Any "gotchas" involved in using this package for SSR that we need to be aware of? Pros and cons of using this package versus Nuxt or Node? 
Also, links to examples where this is working well for you would be helpful as well....depending on how much help you'd like to provide here. It's all useful and appreciated.

**Comment by timrspratt** [comment]
SSR with PHP and Vapor is something we're keen to get an answer for but we'd need to know more about the PHP build Vapor uses. If V8 is included then SSR should be possible, by changing the engine to V8js. If not, then I'm not sure yet how PHP can access Node. Somebody with more of an understanding of Lambda and getting PHP to run on it may know.

**Comment by jcsoriano** [comment]
I see that this might be the container that Vapor uses: https://github.com/laravel/vapor-php-build/

Anyone knowledgeable with Docker / Lambda / Vapor know if this package will work with this container?

**Comment by BurningDog** [comment]
From the README: `The server-side-rendering library ships with V8 and Node engines.` Looks like setting the path to the `node` binary will work. Going through the docker file from https://github.com/laravel/vapor-php-build/ it doesn't look like v8js is included in the php build.

I'm hoping to deploy a new project to Vapor something in the next month; will test SSR then.

**Comment by jcsoriano** [comment]
I checked the files in https://github.com/laravel/vapor-php-build/ and if I'm not mistaken node isn't included there either, but looking forward to know how your testing goes with Vapor + SSR next month

**Comment by BurningDog** [comment]
Node won't be in the vapor-php-build but is around _somewhere_ because `npm run prod` needs to run in order to create the javascript and css files.

**Comment by jcsoriano** [comment]
I've tried Vapor on a non-SSR project, and the build process (`npm run prod` etc) happens where you run `vapor deploy` from. So if you run it in your local or CI, it'll build there and only deploy the compiled files, as opposed to building it inside the Lambda container

**Comment by 60days** [comment]
I'm working on something completely unrelated that also needs Node in Vapor, but I thought my research might be of interest: With Vapor the original runtime is PHP, so you would need to include a compiled node binary as a custom runtime. 

Luckily LambCI have one here: https://github.com/lambci/node-custom-lambda. You can add it as a 'layer' so you don't need to ship it with the function code (otherwise you hit the 25MB limit very fast - tbh with node_modules it will be hard to stay under the 250MB overall limit!). You can see an example of adding layers to the vapor.yml file at the bottom here: https://github.com/laravel/vapor-php-build/issues/3#issuecomment-541922252

My project is still in the planning phase, so I can't confirm this all works yet, but thats the theory!
