### ISSUE TITLE
What about <head> and meta tags ? 

### ISSUE THREAD

**Issue by ahmed-aliraqi** [spatie/laravel-server-side-rendering#51]

**Comment by Sense** [comment]
Hello @sebastiandedeyne, the main purpose of the SSR is, indeed, to make the SEO tags rendered before executing JS. So in order to make this work, we would like to make the `<head>` meta tags compatible with the [https://github.com/nfl/react-helmet](React-helmet) package. In the `app-server.js` file, the main idea is to dispatch the `const helmet = Helmet.renderStatic();` variable and make it available in the rendered `*.blade.php` file in order to pass the SEO tags in the `head` tags.

Do you think it's possible to make this achievement easily, or offering another working solution? Thanks!

**Comment by jcsoriano** [comment]
Pardon my ignorance, but isn't a workaround just to simply set the meta tags for the initial render via blade / PHP, and then if we need to change the meta tags on the fly (e.g. for an SPA) then we use a package like react-helmet / vue-meta? (though aside from `<title>`, I'm not even sure why we need to change meta tags on-the-fly since scrapers only get the initial values of the meta tags, right?)

**Comment by t08-apporio** [comment]
@sebastiandedeyne has this become a part of the package?
