### ISSUE TITLE
ssr, client js rerenders

### ISSUE THREAD

**Issue by Venipa** [spatie/laravel-server-side-rendering#54]
is there a fix to prevent the rerender or maybe just move the ssr rendered dom

**Comment by jcsoriano** [comment]
If what you mean by "rerender" is client-side hydration, as far as I know client-side hydration is necessary even if you SSR, in order to make it reactive.

You can skip client-side hydration for parts that you don't need to be reactive using a package like https://github.com/maoberlehner/vue-lazy-hydration

That way, you can do:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/5937317/80099081-79073b00-85a0-11ea-8605-c48217380bd8.png">

(screenshot from package's readme)
